#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'launch-turtlebot-gazebo','console_scripts','add_bot_node'
__requires__ = 'launch-turtlebot-gazebo'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('launch-turtlebot-gazebo', 'console_scripts', 'add_bot_node')()
    )
