services:
    app: 
        image: dashing_baseline:latest
        stdin_open: true
        tty: true
        build: .
        user: choirbot
        privileged: true
        environment: 
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ./:/home/choirbot/dev_ws/src
        network_mode: host
        deploy: 
            resources: 
                reservations:
                    devices: 
                    -   driver: nvidia
                        count: all
                        capabilities: [gpu]
